; ╔══════════════════════════════════════════════════════════════╗
; ║        Gammastep — Filtro de Luz Azul                        ║
; ╚══════════════════════════════════════════════════════════════╝

[General]
temp-day=6500
temp-night=3500
transition=1
location-provider=manual
adjustment-method=wayland

[Manual]
lat=-34.6
lon=-58.4
