# ╔══════════════════════════════════════════════════════════════╗
# ║        Variables de Entorno para Integración Wayland        ║
# ╚══════════════════════════════════════════════════════════════╝

# Forzar ejecuciones nativas en Wayland (Firefox, Electron, GTK, Qt)
ELECTRON_OZONE_PLATFORM_HINT=auto
MOZ_ENABLE_WAYLAND=1
MOZ_DISABLE_RDD_SANDBOX=1
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_TYPE=wayland
QT_QPA_PLATFORM="wayland;xcb"
GDK_BACKEND="wayland,x11,*"

# Aceleración por Hardware GPU (AMD Radeon Vega / Mesa)
LIBVA_DRIVER_NAME=radeonsi
VDPAU_DRIVER=radeonsi
MESA_LOADER_DRIVER_OVERRIDE=radeonsi
AMD_VULKAN_ICD=RADV
RADV_PERFTEST=aco
