# ╔══════════════════════════════════════════════════════════════╗
# ║        Variables de Entorno para Integración Wayland        ║
# ╚══════════════════════════════════════════════════════════════╝

# Forzar ejecuciones nativas en Wayland (Firefox, Electron, GTK, Qt)
ELECTRON_OZONE_PLATFORM_HINT=auto
MOZ_ENABLE_WAYLAND=1
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_TYPE=wayland
QT_QPA_PLATFORM="wayland;xcb"
GDK_BACKEND="wayland,x11,*"
