image=~/Pictures/1.jpg
scaling=fill
color={{colors.background.default.hex_stripped}}

indicator-idle-visible
indicator-radius=110
indicator-thickness=10

inside-color={{colors.surface.default.hex_stripped}}D0
inside-clear-color={{colors.surface.default.hex_stripped}}D0
inside-ver-color={{colors.surface.default.hex_stripped}}D0
inside-wrong-color={{colors.surface.default.hex_stripped}}D0

ring-color={{colors.primary.default.hex_stripped}}A0
ring-clear-color={{colors.secondary.default.hex_stripped}}A0
ring-ver-color={{colors.primary_container.default.hex_stripped}}A0
ring-wrong-color={{colors.error.default.hex_stripped}}A0

key-hl-color={{colors.on_surface.default.hex_stripped}}
bs-hl-color={{colors.error.default.hex_stripped}}

text-color={{colors.on_surface.default.hex_stripped}}
text-clear-color={{colors.on_secondary.default.hex_stripped}}
text-ver-color={{colors.on_primary_container.default.hex_stripped}}
text-wrong-color={{colors.on_error.default.hex_stripped}}

line-color=00000000
separator-color=00000000

font=Inter
font-size=16

show-failed-attempts
ignore-empty-password
daemonize
