[colors-dark]
alpha=0.88
foreground=dde4e3
background=0e1415
selection-foreground=003738
selection-background=80d4d7
cursor=0e1415 80d4d7
urls=80d4d7

# Paleta ANSI de Texto Armonizada con Matugen Material 3
regular0=1a2121
regular1=ffb4ab
regular2=b5c7e9
regular3=b0cccc
regular4=80d4d7
regular5=004f52
regular6=324b4c
regular7=dde4e3

bright0=899393
bright1=93000a
bright2=354763
bright3=cce8e8
bright4=9cf1f4
bright5=d5e3ff
bright6=bec8c8
bright7=dde4e3
