[colors-dark]
alpha=1.0
foreground=e2e2e2
background=131313
selection-foreground=002e69
selection-background=adc6ff
cursor=131313 adc6ff
urls=adc6ff

# Paleta ANSI de Texto Armonizada con Matugen Material 3
regular0=1f1f1f
regular1=ffb4ab
regular2=debcdf
regular3=bfc6dc
regular4=adc6ff
regular5=0f448e
regular6=3f4759
regular7=e2e2e2

bright0=919191
bright1=93000a
bright2=583e5b
bright3=dbe2f9
bright4=d8e2ff
bright5=fbd7fc
bright6=c6c6c6
bright7=e2e2e2

[colors-light]
alpha=1.0
foreground=e2e2e2
background=131313
selection-foreground=002e69
selection-background=adc6ff
cursor=131313 adc6ff
urls=adc6ff

regular0=1f1f1f
regular1=ffb4ab
regular2=debcdf
regular3=bfc6dc
regular4=adc6ff
regular5=0f448e
regular6=3f4759
regular7=e2e2e2

bright0=919191
bright1=93000a
bright2=583e5b
bright3=dbe2f9
bright4=d8e2ff
bright5=fbd7fc
bright6=c6c6c6
bright7=e2e2e2
