[colors-dark]
alpha=0.88
foreground=e3e3d8
background=12140e
selection-foreground=233600
selection-background=b5d086
cursor=12140e b5d086
urls=b5d086

# Paleta ANSI de Texto Armonizada con Matugen Material 3
regular0=1e2019
regular1=ffb4ab
regular2=a0d0c9
regular3=c1caab
regular4=b5d086
regular5=384d12
regular6=414a32
regular7=e3e3d8

bright0=8f9284
bright1=93000a
bright2=1f4e49
bright3=dde6c6
bright4=d1eca0
bright5=bcece5
bright6=c5c8b9
bright7=e3e3d8
