[colors-dark]
alpha=0.88
foreground=e9e0e7
background=161217
selection-foreground=432254
selection-background=e2b7f4
cursor=161217 e2b7f4
urls=e2b7f4

# Paleta ANSI de Texto Armonizada con Matugen (Material 3)
regular0=221e24
regular1=ffb4ab
regular2=f5b7b6
regular3=d4c0d8
regular4=e2b7f4
regular5=5b396c
regular6=504255
regular7=e9e0e7

bright0=978e97
bright1=93000a
bright2=663b3b
bright3=f0dcf4
bright4=f6d9ff
bright5=ffdad9
bright6=cec3ce
bright7=e9e0e7
